/// <reference types="next" />
/// <reference types="next/types/global" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited manually
// This file is automatically generated by the Next.js typescript setup
// Ensures TypeScript checks and autocompletion works properly within the Next.js app