import { NextApiRequest, NextApiResponse } from "next";
import { StatesCounties } from "../../types/dashboard";

// Real US states and counties data
const statesCountiesData: StatesCounties = {
  states: [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
  ],
  counties: {
    Washington: [
      "King",
      "Pierce",
      "Snohomish",
      "Spokane",
      "Clark",
      "Thurston",
      "Kitsap",
      "Whatcom",
      "Skagit",
      "Cowlitz",
    ],
    California: [
      "Los Angeles",
      "San Diego",
      "Orange",
      "Riverside",
      "San Bernardino",
      "Santa Clara",
      "Alameda",
      "Sacramento",
      "Contra Costa",
      "Fresno",
    ],
    Texas: [
      "Harris",
      "Dallas",
      "Tarrant",
      "Bexar",
      "Travis",
      "Collin",
      "Hidalgo",
      "El Paso",
      "Denton",
      "Fort Bend",
    ],
    "New York": [
      "Kings",
      "Queens",
      "New York",
      "Suffolk",
      "Bronx",
      "Nassau",
      "Westchester",
      "Erie",
      "Monroe",
      "Richmond",
    ],
    Florida: [
      "Miami-Dade",
      "Broward",
      "Palm Beach",
      "Hillsborough",
      "Orange",
      "Pinellas",
      "Duval",
      "Lee",
      "Polk",
      "Brevard",
    ],
    Illinois: [
      "Cook",
      "DuPage",
      "Lake",
      "Will",
      "Kane",
      "McHenry",
      "Winnebago",
      "Madison",
      "St. Clair",
      "Champaign",
    ],
    Pennsylvania: [
      "Philadelphia",
      "Allegheny",
      "Montgomery",
      "Bucks",
      "Chester",
      "Delaware",
      "Lancaster",
      "York",
      "Berks",
      "Westmoreland",
    ],
    Ohio: [
      "Cuyahoga",
      "Franklin",
      "Hamilton",
      "Summit",
      "Montgomery",
      "Lucas",
      "Stark",
      "Butler",
      "Lorain",
      "Mahoning",
    ],
    Georgia: [
      "Fulton",
      "Gwinnett",
      "DeKalb",
      "Cobb",
      "Clayton",
      "Cherokee",
      "Henry",
      "Forsyth",
      "Hall",
      "Houston",
    ],
    "North Carolina": [
      "Mecklenburg",
      "Wake",
      "Guilford",
      "Forsyth",
      "Cumberland",
      "Durham",
      "Buncombe",
      "Union",
      "New Hanover",
      "Gaston",
    ],
    Michigan: [
      "Wayne",
      "Oakland",
      "Macomb",
      "Kent",
      "Genesee",
      "Washtenaw",
      "Ottawa",
      "Ingham",
      "Kalamazoo",
      "Saginaw",
    ],
    "New Jersey": [
      "Bergen",
      "Middlesex",
      "Essex",
      "Hudson",
      "Monmouth",
      "Ocean",
      "Union",
      "Passaic",
      "Camden",
      "Morris",
    ],
    Virginia: [
      "Fairfax",
      "Virginia Beach",
      "Prince William",
      "Chesterfield",
      "Henrico",
      "Norfolk",
      "Loudoun",
      "Chesapeake",
      "Richmond",
      "Newport News",
    ],
    Arizona: [
      "Maricopa",
      "Pima",
      "Pinal",
      "Yavapai",
      "Mohave",
      "Coconino",
      "Yuma",
      "Cochise",
      "Navajo",
      "Apache",
    ],
    Tennessee: [
      "Shelby",
      "Davidson",
      "Knox",
      "Hamilton",
      "Rutherford",
      "Williamson",
      "Montgomery",
      "Sumner",
      "Wilson",
      "Blount",
    ],
    Indiana: [
      "Marion",
      "Lake",
      "Allen",
      "Hamilton",
      "St. Joseph",
      "Vanderburgh",
      "Elkhart",
      "Tippecanoe",
      "Porter",
      "Madison",
    ],
    Massachusetts: [
      "Middlesex",
      "Worcester",
      "Essex",
      "Suffolk",
      "Norfolk",
      "Bristol",
      "Plymouth",
      "Hampden",
      "Barnstable",
      "Hampshire",
    ],
    Maryland: [
      "Montgomery",
      "Prince George's",
      "Baltimore",
      "Anne Arundel",
      "Howard",
      "Baltimore City",
      "Harford",
      "Frederick",
      "Carroll",
      "Charles",
    ],
    Wisconsin: [
      "Milwaukee",
      "Dane",
      "Waukesha",
      "Brown",
      "Racine",
      "Outagamie",
      "Winnebago",
      "Washington",
      "Kenosha",
      "Rock",
    ],
    Colorado: [
      "Denver",
      "El Paso",
      "Jefferson",
      "Arapahoe",
      "Adams",
      "Boulder",
      "Larimer",
      "Douglas",
      "Pueblo",
      "Mesa",
    ],
    Minnesota: [
      "Hennepin",
      "Ramsey",
      "Dakota",
      "Anoka",
      "Washington",
      "Wright",
      "St. Louis",
      "Olmsted",
      "Scott",
      "Carver",
    ],
    "South Carolina": [
      "Greenville",
      "Richland",
      "Charleston",
      "Lexington",
      "Horry",
      "Spartanburg",
      "York",
      "Anderson",
      "Beaufort",
      "Berkeley",
    ],
    Alabama: [
      "Jefferson",
      "Mobile",
      "Madison",
      "Montgomery",
      "Tuscaloosa",
      "Baldwin",
      "Shelby",
      "Morgan",
      "Calhoun",
      "Houston",
    ],
    Louisiana: [
      "Jefferson",
      "Orleans",
      "East Baton Rouge",
      "Caddo",
      "Lafayette",
      "St. Tammany",
      "Calcasieu",
      "Tangipahoa",
      "Rapides",
      "Terrebonne",
    ],
    Kentucky: [
      "Jefferson",
      "Fayette",
      "Kenton",
      "Boone",
      "Warren",
      "Daviess",
      "Campbell",
      "Hardin",
      "Madison",
      "McCracken",
    ],
    Oregon: [
      "Multnomah",
      "Washington",
      "Clackamas",
      "Lane",
      "Marion",
      "Jackson",
      "Deschutes",
      "Yamhill",
      "Linn",
      "Douglas",
    ],
    Oklahoma: [
      "Oklahoma",
      "Tulsa",
      "Cleveland",
      "Comanche",
      "Canadian",
      "Creek",
      "Garfield",
      "McClain",
      "Rogers",
      "Wagoner",
    ],
    Connecticut: [
      "Fairfield",
      "Hartford",
      "New Haven",
      "New London",
      "Litchfield",
      "Middlesex",
      "Tolland",
      "Windham",
    ],
    Iowa: [
      "Polk",
      "Linn",
      "Scott",
      "Johnson",
      "Black Hawk",
      "Woodbury",
      "Dubuque",
      "Story",
      "Dallas",
      "Pottawattamie",
    ],
    Mississippi: [
      "Hinds",
      "Harrison",
      "DeSoto",
      "Jackson",
      "Madison",
      "Rankin",
      "Forrest",
      "Lee",
      "Lauderdale",
      "Jones",
    ],
    Arkansas: [
      "Pulaski",
      "Washington",
      "Benton",
      "Faulkner",
      "Jefferson",
      "Craighead",
      "Saline",
      "Sebastian",
      "Garland",
      "White",
    ],
    Kansas: [
      "Johnson",
      "Sedgwick",
      "Shawnee",
      "Wyandotte",
      "Douglas",
      "Leavenworth",
      "Butler",
      "Reno",
      "Riley",
      "Ford",
    ],
    Utah: [
      "Salt Lake",
      "Utah",
      "Davis",
      "Weber",
      "Washington",
      "Cache",
      "Iron",
      "Tooele",
      "Box Elder",
      "Summit",
    ],
    Nevada: [
      "Clark",
      "Washoe",
      "Carson City",
      "Lyon",
      "Elko",
      "Douglas",
      "Nye",
      "Churchill",
      "Humboldt",
      "White Pine",
    ],
    "New Mexico": [
      "Bernalillo",
      "Dona Ana",
      "Santa Fe",
      "Sandoval",
      "San Juan",
      "Valencia",
      "Lea",
      "Otero",
      "Eddy",
      "Rio Arriba",
    ],
    "West Virginia": [
      "Kanawha",
      "Cabell",
      "Wood",
      "Monongalia",
      "Raleigh",
      "Berkeley",
      "Jefferson",
      "Ohio",
      "Putnam",
      "Marion",
    ],
    Nebraska: [
      "Douglas",
      "Lancaster",
      "Sarpy",
      "Hall",
      "Buffalo",
      "Dodge",
      "Madison",
      "Platte",
      "Scotts Bluff",
      "Lincoln",
    ],
    Idaho: [
      "Ada",
      "Canyon",
      "Kootenai",
      "Bonneville",
      "Twin Falls",
      "Bannock",
      "Nez Perce",
      "Madison",
      "Cassia",
      "Elmore",
    ],
    Hawaii: ["Honolulu", "Hawaii", "Maui", "Kauai"],
    "New Hampshire": [
      "Hillsborough",
      "Rockingham",
      "Merrimack",
      "Strafford",
      "Cheshire",
      "Grafton",
      "Carroll",
      "Belknap",
      "Sullivan",
      "Coos",
    ],
    Maine: [
      "Cumberland",
      "York",
      "Penobscot",
      "Kennebec",
      "Androscoggin",
      "Aroostook",
      "Oxford",
      "Somerset",
      "Hancock",
      "Knox",
    ],
    "Rhode Island": ["Providence", "Kent", "Washington", "Newport", "Bristol"],
    Montana: [
      "Yellowstone",
      "Missoula",
      "Gallatin",
      "Flathead",
      "Cascade",
      "Lewis and Clark",
      "Ravalli",
      "Silver Bow",
      "Lake",
      "Park",
    ],
    Delaware: ["New Castle", "Kent", "Sussex"],
    "South Dakota": [
      "Minnehaha",
      "Pennington",
      "Lincoln",
      "Brown",
      "Codington",
      "Brookings",
      "Lawrence",
      "Beadle",
      "Yankton",
      "Meade",
    ],
    "North Dakota": [
      "Cass",
      "Burleigh",
      "Grand Forks",
      "Ward",
      "Morton",
      "Stark",
      "Williams",
      "Stutsman",
      "Richland",
      "Barnes",
    ],
    Alaska: [
      "Anchorage",
      "Fairbanks North Star",
      "Matanuska-Susitna",
      "Kenai Peninsula",
      "Juneau",
      "Bethel",
      "Northwest Arctic",
      "Nome",
      "North Slope",
      "Southeast Fairbanks",
    ],
    Vermont: [
      "Chittenden",
      "Rutland",
      "Washington",
      "Windsor",
      "Windham",
      "Franklin",
      "Addison",
      "Bennington",
      "Orange",
      "Lamoille",
    ],
    Wyoming: [
      "Laramie",
      "Natrona",
      "Campbell",
      "Sweetwater",
      "Fremont",
      "Albany",
      "Sheridan",
      "Carbon",
      "Uinta",
      "Lincoln",
    ],
  },
};

export default async function handler(req: NextApiRequest, res: NextApiResponse<StatesCounties>) {
  if (req.method !== "GET") {
    return res.status(405).json({ error: "Method not allowed" } as any);
  }

  try {
    res.status(200).json(statesCountiesData);
  } catch (error) {
    console.error("Error fetching locations:", error);
    res.status(500).json({ error: "Failed to fetch locations" } as any);
  }
}
